version: '3.1'
services:
    mysqldb:
        image: mysql
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        container_name: "mysqldb"
        ports:
           - '3306:3306'
    adminer:
        image: adminer
        restart: always
        container_name: "adminer"
        ports:
            - '8080:8080'
        depends_on:
            - mysqldb   
    web:
        image: muraric/imathas:1.1
        container_name: "webapp"
        ports:
            - '80:80'
        depends_on:
            - mysqldb