version: '8.0.40-debian'
services:
    mysqldb:
        image: mysql
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        container_name: "mysqldb"
        volumes:
           - db-data:/var/lib/mysql
        ports:
           - '3306:3306'
    adminer:
        image: adminer
        restart: always
        container_name: "adminer"
        ports:
            - '8080:8080'
        depends_on:
            - mysqldb   
    web:
        image: muraric/imathas:1.1
        restart: always
        container_name: "webapp"
        volumes:
            - web-data:/var/www/html
        ports:
            - '80:80'
        depends_on:
            - mysqldb
volumes:
    db-data:
    web-data:
